import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My paintings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Buy my paintings
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Image src="/images/1.jpg" alt='image' width={200} height={100}></Image>
            <p>Just buy it! #1</p>
          </a>
        </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Image src="/images/2.jpg" alt='image' width={200} height={100}></Image>
            <p>Just buy it! #2</p>
          </a>
        </div>
      </main>

    </div>
  )
}
