import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { checkout } from '../checkout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My paintings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Buy my paintings
        </h1>

        <div className={styles.grid}>
          <div>
            <Image src="/images/1.jpg" alt='image' width={200} height={100}></Image>
            <p>Just buy it! #1</p>
            <button onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1MEYIPIDY5IDtydUA39NPJKe",
                    quantity: 1
                  }
                ]
              })
            }}>Buy!</button>
          </div>
        </div>
        <div className={styles.grid}>
        <div>
            <Image src="/images/2.jpg" alt='image' width={200} height={100}></Image>
            <p>Just buy it! #1</p>
            <button onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1MEYJeIDY5IDtydUyXVb9U0m",
                    quantity: 1
                  }
                ]
              })
            }}>Buy!</button>
          </div>
        </div>
      </main>

    </div>
  )
}
